version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        links:
            - db:db
        depends_on:
            - db

    db:
        image: postgres:14
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
