version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./compose/production/Dockerfile
        volumes:
            - .:/app
            - static_files:/app/static/

    nginx:
        build:
            context: .
            dockerfile: ./compose/nginx/Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - app:app
        volumes:
            - static_files:/static/
            - ./certificates/:/certificates/
        depends_on:
            - app

volumes:
    static_files:
